app-web:  
  build: ./web
  ports:
    - "8081:8080"
  links:
    - app-db

app-db:  
  build: ./db
  expose:
    - "5432"
  volumes:
    - ./opt/postgresql/data:/var/lib/postgresql/data

#app-db-data:  
#  image: cogniteev/echo
#  command: echo 'Data Container for PostgreSQL'
#  volumes:
#    - /var/lib/postgresql/data
